Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/product_handler_spec.rb'
    - 'spec/features/vending_machine_spec.rb'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Exclude:
     - 'lib/vending_machine.rb'

Style/NumericPredicate:
  Exclude:
    - 'lib/vending_machine.rb'
